@startuml
abstract class com.dutianze.designpattern.creational.prototype.hero.Mage {
+ {abstract}Mage copy()
}
class com.dutianze.designpattern.creational.prototype.hero.impl.ElfMage {
- String helpType
+ ElfMage copy()
+ String toString()
}
class com.dutianze.designpattern.creational.prototype.hero.impl.ElfBeast {
- String helpType
+ ElfBeast copy()
+ String toString()
}
class com.dutianze.designpattern.creational.prototype.hero.impl.ElfWarlord {
- String helpType
+ ElfWarlord copy()
+ String toString()
}
interface com.dutianze.designpattern.creational.prototype.factory.HeroFactory {
~ Mage createMage()
~ Warlord createWarlord()
~ Beast createBeast()
}
interface com.dutianze.designpattern.creational.prototype.Prototype {
~ Object copy()
}
class com.dutianze.designpattern.creational.prototype.hero.impl.OrcBeast {
- String weapon
+ OrcBeast copy()
+ String toString()
}
class com.dutianze.designpattern.creational.prototype.hero.impl.OrcWarlord {
- String weapon
+ OrcWarlord copy()
+ String toString()
}
class com.dutianze.designpattern.creational.prototype.factory.HeroFactoryImpl {
- Mage mage
- Warlord warlord
- Beast beast
+ Mage createMage()
+ Warlord createWarlord()
+ Beast createBeast()
}
class com.dutianze.designpattern.creational.prototype.hero.impl.OrcMage {
- String weapon
+ OrcMage copy()
+ String toString()
}
abstract class com.dutianze.designpattern.creational.prototype.hero.Beast {
+ {abstract}Beast copy()
}
abstract class com.dutianze.designpattern.creational.prototype.hero.Warlord {
+ {abstract}Warlord copy()
}


com.dutianze.designpattern.creational.prototype.Prototype <|.. com.dutianze.designpattern.creational.prototype.hero.Mage
com.dutianze.designpattern.creational.prototype.hero.Mage <|-- com.dutianze.designpattern.creational.prototype.hero.impl.ElfMage
com.dutianze.designpattern.creational.prototype.hero.Beast <|-- com.dutianze.designpattern.creational.prototype.hero.impl.ElfBeast
com.dutianze.designpattern.creational.prototype.hero.Warlord <|-- com.dutianze.designpattern.creational.prototype.hero.impl.ElfWarlord
com.dutianze.designpattern.creational.prototype.hero.Beast <|-- com.dutianze.designpattern.creational.prototype.hero.impl.OrcBeast
com.dutianze.designpattern.creational.prototype.hero.Warlord <|-- com.dutianze.designpattern.creational.prototype.hero.impl.OrcWarlord
com.dutianze.designpattern.creational.prototype.factory.HeroFactory <|.. com.dutianze.designpattern.creational.prototype.factory.HeroFactoryImpl
com.dutianze.designpattern.creational.prototype.hero.Mage <|-- com.dutianze.designpattern.creational.prototype.hero.impl.OrcMage
com.dutianze.designpattern.creational.prototype.Prototype <|.. com.dutianze.designpattern.creational.prototype.hero.Beast
com.dutianze.designpattern.creational.prototype.Prototype <|.. com.dutianze.designpattern.creational.prototype.hero.Warlord
@enduml