@startuml
class com.dutianze.designpattern.creational.abstractfactory.kingdom.orc.OrcKing {
+ String getDescription()
}
interface com.dutianze.designpattern.creational.abstractfactory.fatory.KingdomFactory {
~ Castle createCastle()
~ King createKing()
~ Army createArmy()
~ Kingdom createKingdom()
~ {static} KingdomFactory makeFactory(KingdomType)
}
enum com.dutianze.designpattern.creational.abstractfactory.fatory.KingdomType {
+  ELF
+  ORC
}
class com.dutianze.designpattern.creational.abstractfactory.kingdom.elf.ElfArmy {
+ String getDescription()
}
class com.dutianze.designpattern.creational.abstractfactory.fatory.impl.OrcKingdomFactory {
+ Castle createCastle()
+ King createKing()
+ Army createArmy()
}
interface com.dutianze.designpattern.creational.abstractfactory.kingdom.King {
~ String getDescription()
}
class com.dutianze.designpattern.creational.abstractfactory.kingdom.elf.ElfCastle {
+ String getDescription()
}
interface com.dutianze.designpattern.creational.abstractfactory.kingdom.Castle {
~ String getDescription()
}
class com.dutianze.designpattern.creational.abstractfactory.fatory.impl.ElfKingdomFactory {
+ Castle createCastle()
+ King createKing()
+ Army createArmy()
}
class com.dutianze.designpattern.creational.abstractfactory.kingdom.Kingdom {
- King king
- Castle castle
- Army army
}
class com.dutianze.designpattern.creational.abstractfactory.kingdom.elf.ElfKing {
+ String getDescription()
}
interface com.dutianze.designpattern.creational.abstractfactory.kingdom.Army {
~ String getDescription()
}
class com.dutianze.designpattern.creational.abstractfactory.kingdom.orc.OrcArmy {
+ String getDescription()
}
class com.dutianze.designpattern.creational.abstractfactory.kingdom.orc.OrcCastle {
+ String getDescription()
}


com.dutianze.designpattern.creational.abstractfactory.kingdom.King <|.. com.dutianze.designpattern.creational.abstractfactory.kingdom.orc.OrcKing
com.dutianze.designpattern.creational.abstractfactory.kingdom.Army <|.. com.dutianze.designpattern.creational.abstractfactory.kingdom.elf.ElfArmy
com.dutianze.designpattern.creational.abstractfactory.fatory.KingdomFactory <|.. com.dutianze.designpattern.creational.abstractfactory.fatory.impl.OrcKingdomFactory
com.dutianze.designpattern.creational.abstractfactory.kingdom.Castle <|.up. com.dutianze.designpattern.creational.abstractfactory.kingdom.elf.ElfCastle
com.dutianze.designpattern.creational.abstractfactory.fatory.KingdomFactory <|.. com.dutianze.designpattern.creational.abstractfactory.fatory.impl.ElfKingdomFactory
com.dutianze.designpattern.creational.abstractfactory.kingdom.King <|.up. com.dutianze.designpattern.creational.abstractfactory.kingdom.elf.ElfKing
com.dutianze.designpattern.creational.abstractfactory.kingdom.Army <|.. com.dutianze.designpattern.creational.abstractfactory.kingdom.orc.OrcArmy
com.dutianze.designpattern.creational.abstractfactory.kingdom.Castle <|.. com.dutianze.designpattern.creational.abstractfactory.kingdom.orc.OrcCastle
@enduml