@startuml
class SimpleTroll {
+ void attack()
+ int getAttackPower()
+ void fleeBattle()
}
class ClubbedTroll {
- Troll decorated
+ void attack()
+ int getAttackPower()
+ void fleeBattle()
}
interface Troll {
~ void attack()
~ int getAttackPower()
~ void fleeBattle()
}


Troll <|.. SimpleTroll
Troll <|.. ClubbedTroll
@enduml