@startuml
class com.dutianze.designpattern.iterator.list.TreasureChest {
- List<Item> items
- ItemType type
+ Iterator<Item> iteratorByType(ItemType)
+ Iterator<Item> iterator()
}
class com.dutianze.designpattern.iterator.list.TreasureChest.TreasureChestItemIterator {
- int idx
+ boolean hasNext()
+ Item next()
- int findNextIdx()
}
class com.dutianze.designpattern.iterator.list.Item {
- ItemType type
- String name
}
enum com.dutianze.designpattern.iterator.list.ItemType {
+  ANY
+  WEAPON
+  RING
+  POTION
}


com.dutianze.designpattern.iterator.list.Iterable <|.. com.dutianze.designpattern.iterator.list.TreasureChest
com.dutianze.designpattern.iterator.list.TreasureChest +.. com.dutianze.designpattern.iterator.list.TreasureChest.TreasureChestItemIterator
com.dutianze.designpattern.iterator.list.Iterator <|.. com.dutianze.designpattern.iterator.list.TreasureChest.TreasureChestItemIterator
@enduml