@startuml
class IvoryTower {
+ void enter(Wizard)
}
class Wizard {
- String name
+ String toString()
}
interface WizardTower {
~ void enter(Wizard)
}
class WizardTowerProxy {
- {static} int NUM_WIZARDS_ALLOWED
- int numWizards
- WizardTower tower
+ void enter(Wizard)
}


WizardTowerProxy -->  "-tower" WizardTower
IvoryTower ..|> WizardTower
WizardTowerProxy ..|> WizardTower
@enduml