@startuml
class Captain {
- RowingBoat rowingBoat
~ void row()
}
class FishingBoat {
~ void sail()
}
class FishingBoatAdapter {
- FishingBoat boat
+ void row()
}
interface RowingBoat {
~ void row()
}


FishingBoatAdapter -->  "-boat" FishingBoat
Captain -->  "-rowingBoat" RowingBoat
FishingBoatAdapter ..|> RowingBoat
@enduml