@startuml
class Hammer {
- Enchantment enchantment
+ void wield()
+ void swing()
+ void unwield()
+ Enchantment getEnchantment()
}
interface Weapon {
~ void wield()
~ void swing()
~ void unwield()
~ Enchantment getEnchantment()
}
class Sword {
- Enchantment enchantment
+ void wield()
+ void swing()
+ void unwield()
+ Enchantment getEnchantment()
}
class SoulEatingEnchantment {
+ void onActivate()
+ void apply()
+ void onDeactivate()
}
class FlyingEnchantment {
+ void onActivate()
+ void apply()
+ void onDeactivate()
}
interface Enchantment {
~ void onActivate()
~ void apply()
~ void onDeactivate()
}


Sword -->  "-enchantment" Enchantment
Hammer -->  "-enchantment" Enchantment
FlyingEnchantment ..|> Enchantment
Hammer ..|> Weapon
SoulEatingEnchantment ..|> Enchantment
Sword ..|> Weapon
@enduml