@startuml
class HitAndRunMethod {
# String pickTarget()
# void confuseTarget(String)
# void stealTheItem(String)
}
abstract class StealingMethod {
# {abstract}String pickTarget()
# {abstract}void confuseTarget(String)
# {abstract}void stealTheItem(String)
+ void steal()
}
class SubtleMethod {
# String pickTarget()
# void confuseTarget(String)
# void stealTheItem(String)
}


StealingMethod <|-- HitAndRunMethod
StealingMethod <|-- SubtleMethod
@enduml