@startuml
abstract class LetterComposite {
- List<LetterComposite> children
+ void add(LetterComposite)
+ int count()
# void printThisBefore()
# void printThisAfter()
+ void print()
}
class Word {
# void printThisBefore()
}
class Letter {
- char character
# void printThisBefore()
}
class Sentence {
# void printThisAfter()
}


LetterComposite <|-- Word
LetterComposite <|-- Letter
LetterComposite <|-- Sentence
@enduml