@startuml
interface Potion {
~ void drink()
}
class PotionFactory {
- Map<PotionType,Potion> potions
~ Potion createPotion(PotionType)
- Potion choosePotion(PotionType)
}
class AlchemistShop {
- List<Potion> shelf
+ List<Potion> getShelf()
}
class StrengthPotion {
+ void drink()
}
class InvisibilityPotion {
+ void drink()
}
enum PotionType {
+  HEALING
+  INVISIBILITY
+  STRENGTH
+  HOLY_WATER
+  POISON
}
class HealingPotion {
+ void drink()
}
class PoisonPotion {
+ void drink()
}
class HolyWaterPotion {
+ void drink()
}


AlchemistShop -->  "-topShelf" Potion
HealingPotion ..|> Potion
HolyWaterPotion ..|> Potion
InvisibilityPotion ..|> Potion
PoisonPotion ..|> Potion
StrengthPotion ..|> Potion
@enduml