@startuml
class ElfWeapon {
- WeaponType weaponType
+ String toString()
}
class OrcBlacksmith {
- {static} Map<WeaponType,OrcWeapon> ORCARSENAL
+ Weapon manufactureWeapon(WeaponType)
+ String toString()
}
enum WeaponType {
+  SHORT_SWORD
+  SPEAR
+  AXE
+  UNDEFINED
- String title
}
interface Weapon {
~ WeaponType getWeaponType()
}
class OrcWeapon {
- WeaponType weaponType
+ String toString()
}
class ElfBlacksmith {
- {static} Map<WeaponType,ElfWeapon> ELFARSENAL
+ Weapon manufactureWeapon(WeaponType)
+ String toString()
}
interface Blacksmith {
~ Weapon manufactureWeapon(WeaponType)
}


ElfWeapon -->  "-weaponType" WeaponType
OrcWeapon -->  "-weaponType" WeaponType
App -->  "-blacksmith" Blacksmith
ElfBlacksmith ..|> Blacksmith
ElfWeapon ..|> Weapon
OrcBlacksmith ..|> Blacksmith
OrcWeapon ..|> Weapon
@enduml